### ISSUE TITLE
Docker Infra checklist

### ISSUE THREAD

**Issue by meeDamian** [lncm/ideas#41]
I've had a lot of stuff happening all around the place, so I want to create this issue to just gather it all together (Perhaps move it to some wiki later)…

🧩 `meeDamian/simple-qemu`
---------------------------

#### **tl;dr:** Fetches `qemu` source, and from it builds static binaries for `amd64` host system.  Result is pushed to Docker registry(ies), and binaries are uploaded to Github Release.

- [x] Get it to build
- [x] Verify it works
- [x] Build multiple versions
	- done: `v3.1.0` `v3.1.1` `v4.0.0` `v4.1.0`
- [x] Create short/floating tags
	- `v4`, `v3`, `v4.0`, `v4.1`, `v3.1`, `arm`, `aarch64`, `latest`, `arm32v7`, `arm64v8`, `enable`, `riscv32`, `riscv64`, etc…
- [x] Create _permanent_ tags
- [x] Push to 🐳 Hub 
- [ ] Push to :octocat: Registry
- [ ] Write proper `README.md`
- [ ] Create short script to generate the `Simple tags` section [the] [way] [most] [repos] [have it]
- [ ] Ask @lncm/lncm for code, and process review
- [ ] Get rid of workflow generation scripts, once :octocat: Actions allows for either:
	- [ ] optional jobs (not steps, nor workflows)
	- [ ] referencing jobs in different workflows
- [ ] (?) Setup cron workflow that attempts to build new `qemu` on new version tag in upstream

[the]: https://hub.docker.com/_/golang
[way]: https://hub.docker.com/_/python
[most]: https://hub.docker.com/_/postgres
[repos]: https://hub.docker.com/_/redis
[have it]: https://hub.docker.com/_/node

🧩 `lncm/berkeleydb`
---------------------

#### **tl;dr:** Pre-builds and packages BerkeleyDB `v4.8.30.NC` into a small container, that later can be reused in `Dockerfile` with sth like:

```Dockerfile
COPY --from=meedamian/berkeleydb:db-4.8.30.NC  /opt/  /opt/
````

- [x] Setup build on :octocat: Actions
- [x] Build for `amd64`, `arm32v7`, and `arm64v8` 
- [x] Push to 🐳 Hub 
- [ ] Push to :octocat: Registry
- [ ] Document build process more in `README.md`(?)
- [ ] Move back to `lncm/` namespace once :octocat: Actions are enabled for the org (see https://github.com/lncm/docker-berkeleydb/pull/11)
- [ ] BDB doesn't use semver, but for consistency _permanent_ tags can behave the same as above `+build`
- [ ] See if it's possible to help consumers emulating CPU arch choose the correct version based on manifest, w/o specifying it verbatim
- [ ] Ask @lncm/lncm for code, and process review

🧩 `lncm/bitcoind`
-------------------

**tl;dr:** Docker image with [Bitcoin Core] client built for `amd64`, `arm32v7`, and `arm64v8`.

- [x] Get it to build on a CI
	- done, but not reliable
- [ ] Split build into jobs
	- [x] 1. Berkeleydb
	- [ ] 2. Finish at `make`
	- [ ] 3. Start at `make check`
	- [ ] Upload places
- [ ] Build a few last, non vulnerable, versions
- [ ] Build for `amd64`, `arm32v7`, and `arm64v8` 
- [ ] Do not upload anything to image registry, until builds of all architecture variants complete green
- [ ] Push to 🐳 Hub 
- [ ] Push to :octocat: Registry
- [ ] Document build process more in `README.md`
- [ ] Document new release process more in `README.md` (or another `.md` file)
- [ ] Move back to `lncm/` namespace once :octocat: Actions are enabled for the org (see https://github.com/lncm/docker-berkeleydb/pull/11)
- [ ] Use `+build` to distinguish internal builds
- [ ] Ask @lncm/lncm for code, and process review
- [ ] (?) Setup cron workflow that attempts to build new `bitcoind` on new non-RC version tag in upstream

[Bitcoin Core]: https://github.com/bitcoin/bitcoin

🧩 `lncm/lnd`
--------------

**tl;dr:** Docker image of a Lightning Network client built for `amd64`, `arm32v7`, and `arm64v8`.

- [ ] Move to :octocat: Actions
- [ ] Create a neutrino variant (if warrants a separate image)
- [ ] Build for `amd64`, `arm32v7`, and `arm64v8` 
- [ ] Use Go `v1.13`
- [ ] Use `-trimpath -mod=readonly`
- [ ] In each build, build each binary twice:
	- [ ] `alpine`
	- [ ] `debian:*-slim`
	- [ ] compare checksums
- [ ] From :octocat: Actions push to 🐳 Hub 
- [ ] From :octocat: Actions push to :octocat: Registry
- [ ] Move back to `lncm/` namespace once :octocat: Actions are enabled for the org (see https://github.com/lncm/docker-berkeleydb/pull/11)
- [ ] Ask @lncm/lncm for code and process review
- [ ] (?) Setup cron workflow that attempts to build new `qemu` on new version tag in upstream

🧩 `lncm/invoicer`
-------------------

**tl;dr:** Utility living on top of `lnd` (and optionally `bitcoind`), that helps with creation of payment-accepting frontends

- [ ] Move to :octocat: Actions
- [ ] Add tests
- [ ] Build for `amd64`, `arm32v7`, and `arm64v8` 
- [ ] Use Go `v1.13`
- [ ] Use `-trimpath -mod=readonly`
- [ ] In each build, build each binary twice:
	- [ ] `alpine`
	- [ ] `debian:*-slim`
	- [ ] compare checksums
- [ ] From :octocat: Actions push to 🐳 Hub 
- [ ] From :octocat: Actions push to :octocat: Registry
- [ ] Move back to `lncm/` namespace once :octocat: Actions are enabled for the org (see https://github.com/lncm/docker-berkeleydb/pull/11)
- [ ] Document a release process
- [ ] Get rid of the `Makefile`(?)
- [ ] Get rid of *BSD platforms (@AnotherDroog?)
- [ ] Ask @lncm/lncm for code and process review

🧩 `lncm/donations`
--------------------

**tl;dr:** A UI that lives on top of invoicer that facilitates receiving BTC & LN donations.

- [ ] Cleanup
	- [ ] Get rid of fluff

🧩 `lncm/invoicer-ui`
----------------------

**tl;dr:** A UI that lives on top of invoicer that facilitates receiving BTC & LN in-store payments.

- [ ] Should probably be renamed to sth along the lines of `merchant-ui`
- [ ] is there anyone actually maintaining it?

🧩 `lncm/noma`
---------------

- [ ] @AnotherDroog : )

🧩 `lncm/pi-factory`
---------------------

- [ ] @nolim1t : )

Other/General TODOs
-------------------

- [ ] Create references from pre-existing issues to points on this list 😅
- [x] Find a way to sync README.md between :octocat:, and 🐳 Hub
	- done: https://github.com/meeDamian/sync-readme
- [x] Write an all-in :octocat: Action to create :octocat: Release, and upload files to it
	- done: https://github.com/meeDamian/github-release
- [ ] Come up with a tagging scheme that never overrides non-short tags (Ex. override of `v4` is desired, while override of `v4.1.0-riscv64` should probably be avoided). First thought is to use [semver-compliant] `+build` scheme.
- [ ] Create template repo for stuff that needs emulation
	- [ ] Golang (pass arch to build using `--build-arg`)
	- [ ] General (register `qemu` using [`meedamian/simple-qemu`])
- [ ] Look into `DOCKER_CONTENT_TRUST=1` (currently @ https://github.com/meeDamian/simple-qemu/issues/5)

[semver-compliant]: https://semver.org/#spec-item-10
[`meedamian/simple-qemu`]: https://github.com/meeDamian/simple-qemu

**Comment by nolim1t** [comment]
## merchant-ui

* no active maintainers as far as I know

## pi-factory 

* legacy box project. Working with latest lnd and bitcoind. Also invoicer to follow

## lnd

* have a neutrino build already on dockerhub

**Comment by meeDamian** [comment]
> have a neutrino build already on dockerhub

I don't think we'll _"have it"_ until it's automated, and auditable.  For what I, and anyone, knows you could've added code that sends you all of the btc there once there's enough deposited on that node ;).

**Comment by nolim1t** [comment]
You're [welcome to audit it](https://gitlab.com/nolim1t/lnd/tree/0.7.1-neutrino)

**Comment by AnotherDroog** [comment]
For what it’s worth, I’m happily using your lnd container @nolim1t

Of course auditing is a core concern for us. In that light, I’d like to see all components within one organization and the same git host. 

That way at least all dependencies can be easily found
